---
development:
  cloud_name: instilla
  api_key: <%= ENV["CLY_API_KEY"] %>
  api_secret: <%= ENV["CLY_API_SEC"] %>
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: instilla
  api_key: <%= ENV["CLY_API_KEY"] %>
  api_secret: <%= ENV["CLY_API_SEC"] %>
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: instilla
  api_key: <%= ENV["CLY_API_KEY"] %>
  api_secret: <%= ENV["CLY_API_SEC"] %>
  enhance_image_tag: true
  static_image_support: false
