development:
  adapter: active_record
  active_record_adapter: postgresql
  database: fustal_development
  username: postgres
  encoding: utf8
  host: localhost
  pool: 5
  port: 5432
  password: galliani  
test:
  adapter: active_record
  active_record_adapter: postgresql
  encoding: utf8
  database: fustal_test
  username: postgres
  host: localhost
  pool: 5
  port: 5432
  password: galliani
  collecting: false
staging:
  adapter: active_record
  active_record_adapter: default
  <% unless ENV['DATABASE_URL'].nil? %>
  <% username, password, host, database = ENV['DATABASE_URL'].scan(%r{//(.*):(.*)@(.*)/(.*)}).first %>
  host:     <%= host %>
  username: <%= username %>
  password: <%= password %>
  database: <%= database %>
  <% end %>  
production:
  adapter: active_record
  active_record_adapter: default
  <% unless ENV['DATABASE_URL'].nil? %>
  <% username, password, host, database = ENV['DATABASE_URL'].scan(%r{//(.*):(.*)@(.*)/(.*)}).first %>
  host:     <%= host %>
  username: <%= username %>
  password: <%= password %>
  database: <%= database %>
  <% end %>  